"""add apis and endpoints

Revision ID: 08095d69c682
Revises: c1962c37a4ff
Create Date: 2026-07-11 20:34:11.251886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08095d69c682'
down_revision: Union[str, None] = 'c1962c37a4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apis',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('environment', sa.Enum('production', 'staging', 'development', name='environment', native_enum=False, length=20), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'deprecated', 'draft', name='apistatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_api_project_name')
    )
    op.create_index(op.f('ix_apis_project_id'), 'apis', ['project_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('api_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='httpmethod', native_enum=False, length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('path_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_status_code', sa.Integer(), nullable=False),
    sa.Column('expected_response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auth_type', sa.Enum('none', 'bearer', 'basic', 'api_key', 'oauth2', name='authtype', native_enum=False, length=20), nullable=False),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id', 'method', 'path', name='uq_endpoint_api_method_path')
    )
    op.create_index(op.f('ix_endpoints_api_id'), 'endpoints', ['api_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoints_api_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_apis_project_id'), table_name='apis')
    op.drop_table('apis')
    # ### end Alembic commands ###
