"""add request history

Revision ID: e7b032eb7b5f
Revises: 08095d69c682
Create Date: 2026-07-11 21:06:30.004240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7b032eb7b5f'
down_revision: Union[str, None] = '08095d69c682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_history',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('api_id', sa.Uuid(), nullable=True),
    sa.Column('endpoint_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='httpmethod', native_enum=False, length=10), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('request_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auth_type', sa.Enum('none', 'bearer', 'basic', 'api_key', 'oauth2', name='authtype', native_enum=False, length=20), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_history_project_id'), 'request_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_request_history_user_id'), 'request_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_history_user_id'), table_name='request_history')
    op.drop_index(op.f('ix_request_history_project_id'), table_name='request_history')
    op.drop_table('request_history')
    # ### end Alembic commands ###
